// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Varta.Store.API.Data;

#nullable disable

namespace Varta.Store.API.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260210195315_AddIpAddressToServerTag")]
    partial class AddIpAddressToServerTag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Varta.Store.Shared.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SteamID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");
                });

            modelBuilder.Entity("Varta.Store.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Будівельні набори"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Запчастини"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Інше"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Фурнітура"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Набори для ремонту"
                        });
                });

            modelBuilder.Entity("Varta.Store.Shared.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("StatusId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Varta.Store.Shared.OrderProductHistory", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderProductHistory");
                });

            modelBuilder.Entity("Varta.Store.Shared.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("OrderStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Очікування"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Оплачено"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Видано"
                        });
                });

            modelBuilder.Entity("Varta.Store.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ServerTagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServerTagId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Код. лок, точильний камінь, лопата, молоток, 4 колоди, топорик, 20 дошок, плоскогубці, пилка, металевий дріт, door kit, пачка цв'яхів",
                            ImageUrl = "small_kit.png",
                            Name = "Маленький буд. набір",
                            Price = 120m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "3 код. лока, точильний камінь, лопата, молоток, 12 колод, топорик, 60 дошок, плоскогубці, 2 пилки, 3 металевих дрота, door kit, 3 пачки цв'яхів",
                            ImageUrl = "medium_kit.png",
                            Name = "Середній буд. набір",
                            Price = 250m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "5 код. локів, 2 бочки, 2 точильних камня, 2 лопати, 2 молотка, 20 колод, 2 топорика, 100 дошок, 2 плоскогубців, 2 пилки, 5 металевих дротів, door kit, 5 пачки цв'яхів",
                            ImageUrl = "large_kit.png",
                            Name = "Великий буд. набір",
                            Price = 400m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "32 каменя, 10 колод, упаковка цвяхів, мотузка, металевий дріт, молоток, кувалда, кирка, прапор 'DayZ'",
                            ImageUrl = "flag_kit.png",
                            Name = "Набір для флагштоку",
                            Price = 150m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Автомобільний радіатор",
                            ImageUrl = "radiator.png",
                            Name = "Радіатор",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Для бензинових двигунів",
                            ImageUrl = "sparkplug.png",
                            Name = "Свічка Запалювання",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Для дизельних двигунів",
                            ImageUrl = "glowplug.png",
                            Name = "Свічка Розжарення",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Вантажний акумулятор",
                            ImageUrl = "battery_truck.png",
                            Name = "Акумулятор до V3S",
                            Price = 60m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Автомобільний акумулятор",
                            ImageUrl = "battery_car.png",
                            Name = "Акумулятор 12В",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Запасне колесо",
                            ImageUrl = "wheel_gunter.png",
                            Name = "Колесо до Gunter 2",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Запасне колесо",
                            ImageUrl = "wheel_m1024.png",
                            Name = "Колесо до M1024",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Description = "Вантажне колесо",
                            ImageUrl = "wheel_v3s_front.png",
                            Name = "Переднє Колесо до V3S",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Вантажне колесо (подвійне)",
                            ImageUrl = "wheel_v3s_rear.png",
                            Name = "Заднє Колесо до V3S",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Запасне колесо",
                            ImageUrl = "wheel_olga.png",
                            Name = "Колесо до Olga24",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Запасне колесо",
                            ImageUrl = "wheel_sarka.png",
                            Name = "Колесо до Sarka120",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "Запасне колесо",
                            ImageUrl = "wheel_ada.png",
                            Name = "Колесо до Ada4x4",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Ремонтний матеріал",
                            ImageUrl = "epoxy.png",
                            Name = "Епоксидна смола",
                            Price = 40m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Повна каністра",
                            ImageUrl = "jerrycan.png",
                            Name = "Каністра з бензином",
                            Price = 25m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Елемент живлення",
                            ImageUrl = "battery_9v.png",
                            Name = "Батарейка 9v",
                            Price = 10m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Інструмент для ремонту",
                            ImageUrl = "blowtorch.png",
                            Name = "Паяльна лампа",
                            Price = 30m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "30 днів. 69 слотів + мисливський ніж + банка консервованих бобів + банка квасу",
                            ImageUrl = "black_set.png",
                            Name = "Чорний сет",
                            Price = 150m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "30 днів. 69 слотів + мисливський ніж + банка консервованих бобів + банка квасу",
                            ImageUrl = "green_set.png",
                            Name = "Зелений сет",
                            Price = 150m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            Description = "Для зберігання речей",
                            ImageUrl = "barrel.png",
                            Name = "Бочка",
                            Price = 60m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            Description = "Дерев'яний ящик",
                            ImageUrl = "crate.png",
                            Name = "Ящик",
                            Price = 15m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Великий намет",
                            ImageUrl = "mil_tent.png",
                            Name = "Військова палатка",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 4,
                            Description = "Середній намет",
                            ImageUrl = "camping_tent.png",
                            Name = "Туристична палатка",
                            Price = 30m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 4,
                            Description = "Sea Chest",
                            ImageUrl = "seachest.png",
                            Name = "Скриня",
                            Price = 25m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 4,
                            Description = "10 слотів під зброю",
                            ImageUrl = "gunrack.png",
                            Name = "Стійка для зброї",
                            Price = 80m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            Description = "Weapon Cleaning Kit",
                            ImageUrl = "cleaning_kit.png",
                            Name = "Набір для чистки зброї",
                            Price = 50m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            Description = "Sewing Kit",
                            ImageUrl = "sewing_kit.png",
                            Name = "Швейний набір",
                            Price = 20m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Leather Sewing Kit",
                            ImageUrl = "leather_kit.png",
                            Name = "Набір інструментів скорняку",
                            Price = 20m,
                            ServerTagId = 1
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Tire Repair Kit",
                            ImageUrl = "tire_kit.png",
                            Name = "Набір для ремонту шин",
                            Price = 20m,
                            ServerTagId = 1
                        });
                });

            modelBuilder.Entity("Varta.Store.Shared.ServerTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("ServerTag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chernarus 3PP"
                        });
                });

            modelBuilder.Entity("Varta.Store.Shared.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("WalletTransaction");
                });

            modelBuilder.Entity("Varta.Store.Shared.Order", b =>
                {
                    b.HasOne("Varta.Store.Shared.AppUser", "AppUser")
                        .WithMany("Orders")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varta.Store.Shared.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("OrderStatus");
                });

            modelBuilder.Entity("Varta.Store.Shared.OrderProductHistory", b =>
                {
                    b.HasOne("Varta.Store.Shared.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varta.Store.Shared.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Varta.Store.Shared.Product", b =>
                {
                    b.HasOne("Varta.Store.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Varta.Store.Shared.ServerTag", "ServerTag")
                        .WithMany()
                        .HasForeignKey("ServerTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ServerTag");
                });

            modelBuilder.Entity("Varta.Store.Shared.WalletTransaction", b =>
                {
                    b.HasOne("Varta.Store.Shared.AppUser", "AppUser")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Varta.Store.Shared.AppUser", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("WalletTransactions");
                });

            modelBuilder.Entity("Varta.Store.Shared.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
